# Generated by Django 3.0.8 on 2020-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileimg',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
