# Generated by Django 3.0.8 on 2020-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
