# Generated by Django 3.0.8 on 2020-07-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooom',
            name='category',
            field=models.CharField(choices=[('INTEREST', 'interest'), ('FOOD', 'food'), ('TECH', 'tech'), ('TRAVEL', 'travel')], default='INTEREST', max_length=20),
        ),
    ]
