# Generated by Django 3.0.8 on 2020-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooom',
            name='bgimage',
            field=models.ImageField(upload_to='room'),
        ),
    ]
