# Generated by Django 3.0.8 on 2020-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatrooom_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooom',
            name='bgimage',
            field=models.URLField(blank=True),
        ),
    ]
