# Generated by Django 3.0.8 on 2020-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='imgmessage',
            field=models.ImageField(blank=True, upload_to='msg'),
        ),
        migrations.AlterField(
            model_name='message',
            name='textmessage',
            field=models.TextField(blank=True),
        ),
    ]
