# Generated by Django 3.0.8 on 2020-08-06 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRooom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=30, unique=True)),
                ('icon', models.ImageField(upload_to='room/icon')),
                ('background', models.ImageField(upload_to='room/background')),
                ('introduction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RooomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.ManyToManyField(to='chatroom.ChatRooom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomMember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgtype', models.CharField(choices=[('TXT', 'TXT'), ('IMG', 'IMG')], default='TXT', max_length=3)),
                ('textmessage', models.TextField(blank=True)),
                ('imgmessage', models.ImageField(blank=True, upload_to='msg')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageAuthor', to=settings.AUTH_USER_MODEL)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageRoom', to='chatroom.ChatRooom')),
            ],
        ),
        migrations.AddField(
            model_name='chatrooom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomCategory', to='chatroom.RooomCategory'),
        ),
        migrations.AddField(
            model_name='chatrooom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
